language: node_js
sudo: true
node_js:
  - "6.11.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
install:
  - npm i -g nodemon pm2 bower npm@latest grunt-cli
  - npm install
  - bower install
script:
  - grunt build